/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface IPaths {
    readonly '/api/v1/token/fat-token': {
        readonly post: IOperations['getFatToken'];
    };
    readonly '/api/v1/session/updating': {
        readonly post: IOperations['refreshUserSessionsById'];
    };
    readonly '/api/v1/auth': {
        readonly post: IOperations['auth'];
    };
}

export interface components {
    readonly schemas: {
        readonly Session: {
            readonly sessionId: string;
        };
        readonly AuthInfoFatTokenResponse: {
            readonly fatToken?: string;
            readonly userInfo?: string;
        };
        readonly UserIdentifier: {
            readonly userId: string;
        };
        readonly UserCredentials: {
            readonly username: string;
            readonly password: string;
        };
        readonly AuthInfoThinTokenResponse: {
            readonly thinToken?: string;
            readonly userInfo?: string;
        };
    };
}

export interface IOperations {
    readonly getFatToken: {
        readonly responses: {
            /** OK */
            readonly 200: {
                readonly content: {
                    readonly '*/*': components['schemas']['AuthInfoFatTokenResponse'];
                };
            };
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['Session'];
            };
        };
    };
    readonly refreshUserSessionsById: {
        readonly responses: {
            /** OK */
            readonly 200: unknown;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['UserIdentifier'];
            };
        };
    };
    readonly auth: {
        readonly responses: {
            /** OK */
            readonly 200: {
                readonly content: {
                    readonly '*/*': components['schemas']['AuthInfoThinTokenResponse'];
                };
            };
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['UserCredentials'];
            };
        };
    };
}

export interface external {}
